### ISSUE TITLE
How to update latest version boto3 services.

### ISSUE THREAD

**Issue by gelius7** [gehadshaat/pyboto3#9]
Finally, I found this! Thanks all.

But I faced that pyboto3 missed functions like 
  'servicecatalog.search_provisioned_products()'

Maybe I guess it was not support latest version AWS boto3 doc.

Do you have a plan for update?
If not, 
How can I update it?

**Comment by gehadshaat** [comment]
@gelius7 yes it's definetly due for an update

I will see if the script (pyboto3/boto3_interface_generator.py) can still run. To upgrade try running the script, it might take a while because it pulls documentation from boto3 doc website. If things changed in the documentation site, script might not work.

**Comment by gehadshaat** [comment]
@gelius7 Just upgraded to latest and released it to Pypi

**Comment by gelius7** [comment]
Did you check the script (pyboto3/boto3_interface_generator.py)?
Sadly, I still have some problem.

I have nothing for result. Cause 'https://boto3.readthedocs.io/en/latest/reference/services/' link broken, I guess.
So, I changed the services_url

```python
def iter_all_services(services_url='https://boto3.readthedocs.io/en/latest/reference/services/'):
    services_url = 'https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/index.html'
...
```

But still not working
```bash
(.env) .env ❯ python3 ./.env/lib/python3.7/site-packages/pyboto3/boto3_interface_generator.py
INFO:root:Generating code for service AccessAnalyzer to ./.env/lib/python3.7/site-packages/pyboto3/accessanalyzer.py
Traceback (most recent call last):
  File "./.env/lib/python3.7/site-packages/pyboto3/boto3_interface_generator.py", line 278, in <module>
    generate_all_services_code(os.path.dirname(__file__))
  File "./.env/lib/python3.7/site-packages/pyboto3/boto3_interface_generator.py", line 193, in generate_all_services_code
    service_soup = generate_service_code(url, dist_filepath)
  File "./.env/lib/python3.7/site-packages/pyboto3/boto3_interface_generator.py", line 160, in generate_service_code
    for line in iter_code_lines(soup):
  File "./.env/lib/python3.7/site-packages/pyboto3/boto3_interface_generator.py", line 255, in iter_code_lines
    for method_name, params, description, request_syntax, return_type, response_syntax, response_structure in iter_method_params(soup):
  File "./.env/lib/python3.7/site-packages/pyboto3/boto3_interface_generator.py", line 113, in iter_method_params
    for method, method_soup in iter_methods(soup.find(id='client')):
  File "./.env/lib/python3.7/site-packages/pyboto3/boto3_interface_generator.py", line 104, in iter_methods
    for method_html in soup.find_all('dl', class_='method'):
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by gehadshaat** [comment]
Can you pull latest version and use python 3.6+

**Comment by gelius7** [comment]
Very good. Thank you.
